dist: bionic
sudo: required
language: csharp
mono: none
dotnet: 3.1.401
solution: Etdb.UserService.AspNetCore.sln

addons:
  apt:
    update: true

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: dotnet-build
      script: dotnet build -c Release
    - stage: test
      name: dotnet-test
      before_install: sudo apt-get update && sudo apt-get install curl -y
      script: ./test.sh